"""
Interpreter — The Runtime Engine
================================
Executes the AST generated by the Parser.
"""

from typing import List, Any
import json
import os
import asyncio
from engine.parser.ast_nodes import (
    Program, Trigger, Stmt,
    SetStmt, OutputStmt, RepeatStmt, IfStmt, WhileStmt,
    CreateFileStmt, WriteFileStmt, CallStmt, SaveStmt, LoadStmt,
    PythonStmt, ShellStmt, ImportStmt, WhenStmt, StartServerStmt,
    Literal, Identifier, VarDecl
)
from engine.capabilities.function_manager import FunctionManager
from engine.capabilities.math_engine import MathEngine
from engine.security.license import LicenseManager, Tier

class Interpreter:
    def __init__(self):
        # SECURITY CHECK
        self.tier = LicenseManager().validate_license()
        
        self.state = {}
        self.out_stream = [] 
        self.brain = FunctionManager()
        self.math = MathEngine()
        self.listeners = [] 
        self.server = None

    def check_pro(self, feature_name: str):
        if self.tier != Tier.PRO:
            print(f"    [LOCKED] Feature '{feature_name}' is PRO only.")
            raise PermissionError(f"Upgrade to use {feature_name}")


    async def run(self, program: Program, entry_point="Ignition"):
        # 0. Learn Skills
        for trig in program.triggers:
            if trig.name != entry_point:
                 self.brain.teach(trig.name, trig.block)

        # 1. Initialize Globals
        for decl in program.globals:
            self.state[decl.name] = decl.value

        # 2. Find Entry Trigger
        trigger = next((t for t in program.triggers if t.name == entry_point), None)
        if not trigger:
            print(f"Trigger '{entry_point}' not found. Starting Event Loop.")
        else:
            await self.execute_block(trigger.block)
            
        # 3. Event Loop (if listeners or server exist)
        if self.listeners or self.server:
            print("[SYSTEM] Entering Event Loop... (Ctrl+C to stop)")
            try:
                while True:
                    await self.tick()
                    await asyncio.sleep(0.1)
            except asyncio.CancelledError:
                print("[SYSTEM] Loop stopped.")
                
    async def tick(self):
        # check listeners
        for l in self.listeners:
             kind, target, val, body = l
             if kind == "VAR":
                 # Check state
                 current = self.state.get(target)
                 # Expect val to be Literal? We need to evaluate it?
                 # If parsed as SetStmt, val was stmt.left (Literal).
                 # Interpreter.evaluate handles Literals.
                 expected = self.evaluate(val)
                 # print(f"[DEBUG] Tick: {target}({current}) vs {expected}")
                 if str(current) == str(expected):
                     print(f"    [EVENT] Triggered {kind} on {target}")
                     await self.execute_block(body)

    async def execute_block(self, block: List[Stmt]):
        for stmt in block:
            await self.execute(stmt)

    async def execute(self, stmt: Stmt):
        method_name = f"visit_{type(stmt).__name__}"
        method = getattr(self, method_name, self.generic_visit)
        if asyncio.iscoroutinefunction(method):
            return await method(stmt)
        return method(stmt)

    def generic_visit(self, node):
        print(f"No visit_{type(node).__name__} method.")

    # ------------------------------------------------------------
    # Visitors
    # ------------------------------------------------------------

    def visit_SetStmt(self, node: SetStmt):
        val_left = self.evaluate(node.left)
        res = val_left
        
        if node.op:
            val_right = self.evaluate(node.right)
            if node.op == "PLUS":
                if isinstance(val_left, list):
                     val_left.append(val_right)
                     res = val_left
                else:
                    res = val_left + val_right
            elif node.op == "MINUS":
                res = val_left - val_right
            elif node.op == "TIMES":
                res = val_left * val_right
            elif node.op == "DIVIDE":
                res = val_left / val_right
            
        self.state[node.target] = res

    def visit_OutputStmt(self, node: OutputStmt):
        val = self.evaluate(node.value)
        self.out_stream.append(str(val))
        print(f"    > {val}")

    async def visit_RepeatStmt(self, node: RepeatStmt):
        count = self.evaluate(node.count)
        if isinstance(count, float): count = int(count)
        if isinstance(count, int):
            for _ in range(count):
                await self.execute_block(node.body)

    async def visit_IfStmt(self, node: IfStmt):
        actual = self.state.get(node.var)
        expected = self.evaluate(node.expected)

        # print(f"    [DEBUG] IF Check: {node.var}({actual}) == {expected} ?")
        if str(actual) == str(expected):
            await self.execute_block(node.body)
        elif node.else_body:
            await self.execute_block(node.else_body)

    async def visit_WhileStmt(self, node: WhileStmt):
        max_safety = 1000
        count = 0
        while count < max_safety:
            actual = self.state.get(node.condition_var)
            expected = self.evaluate(node.condition_val)
            if str(actual) == str(expected):
                await self.execute_block(node.body)
                count += 1
                await asyncio.sleep(0.01)
            else:
                break
        if count >= max_safety:
            print("[WARN] While loop terminated for safety.")

    def visit_CreateFileStmt(self, node: CreateFileStmt):
        with open(node.filename, 'w') as f:
            f.write("")
        print(f"    [DISK] Created {node.filename}")

    def visit_WriteFileStmt(self, node: WriteFileStmt):
        content = str(self.evaluate(node.content))
        with open(node.filename, 'w') as f: 
            f.write(content)
            f.write(content)
        print(f"    [DISK] Wrote to {node.filename}")

    async def visit_CallStmt(self, node: CallStmt):
        skill = self.brain.recall(node.func_name)
        if skill:
            print(f"    [CALL] Executing skill '{node.func_name}'")
            await self.execute_block(skill.block)
        else:
            print(f"    [CALL] Skill '{node.func_name}' not found.")

    def visit_SaveStmt(self, node: SaveStmt):
        try:
            self.check_pro("Persistence (Save)")
            with open(node.filename, 'w') as f:
                json.dump(self.state, f, indent=2)
            print(f"    [DISK] State saved to {node.filename}")
        except Exception as e:
            print(f"    [ERR] Save failed: {e}")

    def visit_LoadStmt(self, node: LoadStmt):
        try:
            self.check_pro("Persistence (Load)")
            with open(node.filename, 'r') as f:
                new_state = json.load(f)
                self.state.update(new_state)
            print(f"    [DISK] State loaded from {node.filename}")
        except Exception as e:
            print(f"    [ERR] Load failed: {e}")

    def visit_PythonStmt(self, node: PythonStmt):
        self.check_pro("Python FFI")
        print("    [PYTHON] Executing raw code...")
        try:
            env = {"state": self.state}
            exec(node.code, env, env) 
        except Exception as e:
            print(f"    [ERR] Python Error: {e}")

    def visit_ShellStmt(self, node: ShellStmt):
        self.check_pro("Shell Integration")
        import subprocess
        print(f"    [SHELL] {node.command}")
        try:
             subprocess.run(node.command, shell=True, check=True)
        except Exception as e:
             print(f"    [ERR] Shell Error: {e}")

    def visit_ImportStmt(self, node: ImportStmt):
        print(f"    [IMPORT] Loading {node.module_name}")
        if not os.path.exists(node.module_name):
             print(f"    [ERR] Module {node.module_name} not found.")
             return
        
        from engine.parser.fuzzy_parser import FuzzyParser
        try:
            with open(node.module_name, 'r') as f:
                code = f.read()
            parser = FuzzyParser()
            prog = parser.parse(code)
            
            # 1. Globals
            for decl in prog.globals:
                self.state[decl.name] = decl.value
                
            # 2. Skills
            if hasattr(self, 'brain') and self.brain:
                for trig in prog.triggers:
                    self.brain.teach(trig.name, trig.block)
            else:
                 print("    [WARN] No Brain found. Functions not imported.")
        except Exception as e:
            print(f"    [ERR] Import Error: {e}")

    def visit_WhenStmt(self, node: WhenStmt):
        self.listeners.append((node.kind, node.target, node.val, node.body))
        print(f"    [EVENT] Listening for {node.kind} on {node.target}")

    async def visit_StartServerStmt(self, node: StartServerStmt):
        self.check_pro("Networking (Server)")
        async def handle(reader, writer):
            data = await reader.read(100)
            message = data.decode()
            print(f"    [SERVER] Received: {message}")
            
            # Fire REQUEST events
            for l in self.listeners:
                kind, target, val, body = l
                if kind == "REQUEST":
                    await self.execute_block(body)
            
            writer.write(b"HTTP/1.1 200 OK\r\n\r\nHello from Assertion Engine")
            await writer.drain()
            writer.close()

        server = await asyncio.start_server(handle, '0.0.0.0', node.port)
        self.server = server
        print(f"    [SERVER] Started on port {node.port}")

    # ------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------

    def evaluate(self, node: Any):
        if isinstance(node, Literal):
            if isinstance(node.value, str) and node.value in self.state:
                return self.state[node.value]
            return node.value
        elif isinstance(node, Identifier):
            return self.state.get(node.name, 0)
        elif isinstance(node, (int, float, str)):
            return node
        return None
