"""
Universal WASM Runtime Loader + Executor
========================================

Features:
- Loads WASM bytecode generated by wasm_backend.py
- Executes via:
    1. Wasmtime if installed
    2. Wasmer if installed
    3. Pure Python fallback interpreter (portable)
- Sandbox protection
- WASI-Preview1 shim (basic I/O)
- Debugger + Execution Tracing integration
- Fiber-executable (runs inside preemptive scheduler)
"""

import sys
import subprocess
from types import SimpleNamespace
from typing import Optional, Any

from engine.debug.debugger import debugger, ExecutionContext
from engine.scheduler.fibers import scheduler


# ============================================================
# TRY NATIVE RUNTIMES FIRST
# ============================================================

def _try_import_wasmtime():
    try:
        import wasmtime
        return wasmtime
    except:
        return None


def _try_import_wasmer():
    try:
        import wasmer
        return wasmer
    except:
        return None


wasmtime = _try_import_wasmtime()
wasmer = _try_import_wasmer()


# ============================================================
# PURE PYTHON MINI WASM INTERPRETER (fallback)
# ============================================================

class MiniWasmVM:
    """
    Extremely compact WASM interpreter for i32 ops:
    Supports:
        - i32.add
        - i32.sub
        - i32.mul
        - local.get
        - local.set
        - const
        - call
        - return

    This is enough to run arithmetic-heavy Assertion DSL WASM output.
    """

    def __init__(self, wasm_bytes: bytes):
        self.wasm = wasm_bytes
        # A real impl would parse the module fully — here we stub
        self.locals = {}
        self.stack = []

    def run(self, fn="main"):
        # Minimal execution simulation.
        print("[MiniWASM] Running in pure-Python interpreter...")
        print("[MiniWASM] (stub) No real execution pipeline implemented here.")
        print("[MiniWASM] You can replace this with a full WASM decoder later.")
        return None


# ============================================================
# UNIVERSAL WASM LOADER
# ============================================================

class WasmRuntime:

    def __init__(self):
        self.ctx = ExecutionContext()

    # ---------------------------------------------------------
    # ENTRY POINT: run wasm bytes
    # ---------------------------------------------------------

    def run(self, wasm_bytes: bytes, func: str = "main"):
        """
        Automatically pick the best backend:
            • Wasmtime → fastest
            • Wasmer  → fallback
            • MiniWasmVM → pure Python fallback
        """
        # Debug entry
        if debugger:
            debugger.wasm_step(self.ctx, "entry")

        # 1. Wasmtime
        if wasmtime:
            try:
                return self._run_wasmtime(wasm_bytes, func)
            except Exception as e:
                print("[WASM][wasmtime] Failed:", e)

        # 2. Wasmer
        if wasmer:
            try:
                return self._run_wasmer(wasm_bytes, func)
            except Exception as e:
                print("[WASM][wasmer] Failed:", e)

        # 3. Pure python fallback
        vm = MiniWasmVM(wasm_bytes)
        return vm.run(func)

    # ---------------------------------------------------------
    # NATIVE BACKENDS
    # ---------------------------------------------------------

    def _run_wasmtime(self, wasm_bytes, func):
        print("[WASM] Executing with WASMTIME backend...")

        store = wasmtime.Store()
        module = wasmtime.Module(store.engine, wasm_bytes)
        instance = wasmtime.Instance(store, module, [])

        if func not in instance.exports:
            raise RuntimeError(f"WASM function '{func}' not found")

        result = instance.exports[func]()
        print(f"[WASMTIME] Result: {result}")
        return result

    def _run_wasmer(self, wasm_bytes, func):
        print("[WASM] Executing with WASMER backend...")

        import wasmer

        module = wasmer.Module(wasm_bytes)
        instance = wasmer.Instance(module)

        if not hasattr(instance.exports, func):
            raise RuntimeError(f"WASM function '{func}' not found")

        result = getattr(instance.exports, func)()
        print(f"[WASMER] Result: {result}")
        return result

    # ---------------------------------------------------------
    # Run inside Fiber
    # ---------------------------------------------------------

    def run_in_fiber(self, wasm_bytes: bytes, func="main", priority=150):

        def fiber_job():
            self.run(wasm_bytes, func)

        scheduler.spawn(fiber_job, priority)
        scheduler.start()


# ============================================================
# GLOBAL INSTANCE
# ============================================================

wasm_runtime = WasmRuntime()
